"""add embedding column to cvs and jobs

Revision ID: f1d4fab49a79
Revises: 82a6269b02fb
Create Date: 2026-03-31 10:19:07.099894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f1d4fab49a79'
down_revision: Union[str, Sequence[str], None] = '82a6269b02fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cvs', sa.Column('embedding', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('jobs', sa.Column('embedding', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'embedding')
    op.drop_column('cvs', 'embedding')
    # ### end Alembic commands ###
